# Generated by Django 4.0.4 on 2022-05-03 04:53

from django.db import migrations, models
import plattuit.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=120, unique=True, verbose_name='correo electrónico')),
                ('username', models.CharField(max_length=30, verbose_name='Nombre de usuario')),
                ('date_joined', models.DateTimeField(default=plattuit.utils.time_zone, verbose_name='fecha de creación de cuenta')),
                ('last_login', models.DateTimeField(verbose_name='último logueo')),
                ('is_active', models.BooleanField(default=True, verbose_name='es activo?')),
                ('is_admin', models.BooleanField(default=False, verbose_name='es administrador?')),
            ],
            options={
                'verbose_name': 'cuenta',
                'verbose_name_plural': 'cuentas',
                'db_table': 'users',
            },
        ),
    ]
