# Generated by Django 4.0.4 on 2022-05-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='es empleado'),
        ),
    ]
