# Generated by Django 4.0.4 on 2022-05-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_login',
            field=models.DateTimeField(verbose_name='último logueo'),
        ),
    ]
