# Generated by Django 4.0.4 on 2022-05-03 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0002_alter_microblog_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='microblog',
            options={'verbose_name': 'microblog', 'verbose_name_plural': 'microblogs'},
        ),
        migrations.AlterModelTable(
            name='microblog',
            table='microblog',
        ),
    ]
