# Generated by Django 4.0.4 on 2022-05-03 17:18

from django.db import migrations, models
import django.db.models.deletion
import plattuit.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('microblog', '0003_alter_microblog_options_alter_microblog_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Vistas')),
                ('interaction', models.PositiveIntegerField(default=0, verbose_name='Interacciones')),
                ('update_time', models.DateTimeField(default=plattuit.utils.time_zone, verbose_name='fecha de actualización')),
                ('microblog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='microblog.microblog')),
            ],
            options={
                'verbose_name': 'Rastreo',
                'verbose_name_plural': 'Rastreos',
                'db_table': 'tracking',
            },
        ),
    ]
